from enum import Enum


class Color(str, Enum):
    """
    Enumeration representing a color that can be used within the Management Firewall
    """

    BLACK = "black"
    CRETE_BLUE = "crete blue"
    BURLYWOOD = "burlywood"
    CYAN = "cyan"
    DARK_GREEN = "dark green"
    KHAKI = "khaki"
    ORCHID = "orchid"
    DARK_ORANGE = "dark orange"
    DARK_SEA_GREEN = "dark sea green"
    PINK = "pink"
    TURQUOISE = "turquoise"
    DARK_BLUE = "dark blue"
    FIREBRICK = "firebrick"
    BROWN = "brown"
    FOREST_GREEN = "forest green"
    GOLD = "gold"
    DARK_GOLD = "dark gold"
    GRAY = "gray"
    DARK_GRAY = "dark gray"
    LIGHT_GREEN = "light green"
    LEMON_CHIFFON = "lemon chiffon"
    CORAL = "coral"
    SEA_GREEN = "sea green"
    SKY_BLUE = "sky blue"
    MAGENTA = "magenta"
    PURPLE = "purple"
    SLATE_BLUE = "slate blue"
    VIOLET_RED = "violet red"
    NAVY_BLUE = "navy blue"
    OLIVE = "olive"
    ORANGE = "orange"
    RED = "red"
    SIENNA = "sienna"
    YELLOW = "yellow"
    GREEN = "green"
